[package]
name = "site"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
log = "0.4.22"
serde = { version = "1.0.215", features = ["derive"] }
simple_logger = { version = "5.0.0", features = ["colors"] }
